# %PLAYER% = the player cheating. %PREFIX% = the prefix of the anticheat you set below. %DEBUG% - dev/check info
Alert:
  Prefix: '&8[&cAnticheat&8]&r'
  Alert-Message: '%PREFIX% &7%PLAYER% flagged &c%CHECK% &8(&c%CHECKTYPE%&8) &8[&c%VL%&8] %DEBUG%'
Punishment:
  LagBack: false
  Command:
    Enabled: true
    Execute: '/kick %PLAYER% %PREFIX% &cUnfair Advantage.'
  Announce:
    Enabled: true
    Message: '%PREFIX% &chas removed &7%PLAYER% &cfor using unfair advantages.'
Mongo:
  Enabled: false
  Hostname: "localhost"
  Port: "0000"
  Database: "anticheat"
  Username: "admin"
  Password: "password"
  LogsFileName: "logs"

