# %PLAYER% = the player cheating. %PREFIX% = the prefix of the anticheat you set below.
Prefix: '&7[&cAnticheat&7]&r'
Punishment:
  LagBack: false
  Command:
    Enabled: true
    Execute: '/kick %PLAYER% %PREFIX% &cUnfair Advantage.'
  Announce:
    Enabled: true
    Message: '%PREFIX% &chas removed &7%PLAYER% &cfor using unfair advantages.'

